= User guide

This is the user guide. In this setup, we will automatically install and configure the operators.

If you already went through the xref:index-admin.adoc[admin guide], you can xref:03-deployment-settings.adoc[skip ahead].

Reminder: You can assume that **everything running in the trustee-operator-system namespace should run in a trusted, separate environment**. Because of the limitations of this ARO workshop, it is not possible to set up two clusters.

[#user-credentials]
== Setting up the environment

[tabs]
====
RHDP workshop::
+
. Go into the terminal on the right and run the following commands:
+
[source,sh,role="execute",subs=attributes+]
----
# Log into azure CLI:
az login --service-principal \
--username={azure_service_principal_id} \
--password={azure_service_principal_password} \
--tenant={azure_tenant_id}

# Export AZURE_RESOURCE_GROUP
export AZURE_RESOURCE_GROUP={azure_resource_group}
----
+
. If you need to use the web UI (not necessary in this workshop):
+
* Navigate to the {aro_console}[Openshift Console, window=blank]
+
* Login as administrator:
+
** *Username:* {aro_kube_username}
+
** *Password:* {aro_kube_password}

ARO::
+
. Make sure you log into the right service principal:
+
[source,sh,role=execute]
----
AZ_CID=$(oc get secrets/azure-credentials -n kube-system -o json | jq -r .data.azure_client_id | base64 -d)

AZ_CS=$(oc get secrets/azure-credentials -n kube-system -o json | jq -r .data.azure_client_secret | base64 -d)

AZ_TID=$(oc get secrets/azure-credentials -n kube-system -o json | jq -r .data.azure_tenant_id | base64 -d)

echo azure_client_id $AZ_CID
echo azure_client_secret $AZ_CS
echo azure_tenant_id $AZ_TID

az login --service-principal -u $AZ_CID -p $AZ_CS --tenant $AZ_TID
----
+
. Export the resource group `export AZURE_RESOURCE_GROUP=your-resource-group` where ARO is deployed. This is **not** the resource group created with the OCP ARO cluster.

Azure::
+
. Make sure you log into the right service principal:
+
[source,sh,role=execute]
----
AZ_CID=$(oc get secrets/azure-credentials -n kube-system -o json | jq -r .data.azure_client_id | base64 -d)

AZ_CS=$(oc get secrets/azure-credentials -n kube-system -o json | jq -r .data.azure_client_secret | base64 -d)

AZ_TID=$(oc get secrets/azure-credentials -n kube-system -o json | jq -r .data.azure_tenant_id | base64 -d)

echo azure_client_id $AZ_CID
echo azure_client_secret $AZ_CS
echo azure_tenant_id $AZ_TID

az login --service-principal -u $AZ_CID -p $AZ_CS --tenant $AZ_TID
----
+
. Export the resource group.
+
[source,sh,role=execute]
----
export AZURE_RESOURCE_GROUP=$(oc get infrastructure/cluster -o jsonpath='{.status.platformStatus.azure.resourceGroupName}')
----
====


[#install]
== Automatically set up the environment

All you need to do is download this script, and let it run till it finishes.

The following scripts sets everything just as in the xref:index-admin.adoc[admin guide], with the following:

* Container signature policy accepts any signed/unsigned image except from the one coming from `quay.io/confidential-devhub`.
** Refer xref:02-configure-trustee.adoc#trustee-cisvp[here] if you want to change it.

* `INITDATA` allows logs, but disallows generic exec.
** Refer xref:02-configure-trustee.adoc#trustee-ip[here] if you want to change OSC `INITDATA`.
** For the OSC operator, updating initdata means updating xref:02-configure-osc.adoc#pp-cm[peer-pods-cm] and then xref:02-configure-osc.adoc#pp-restart[restart the daemonset].
** For the Trustee operator, updating initdata means updating Trustee `PCR8` in the xref:02-configure-trustee.adoc#trustee-refval[reference values], otherwise attestation will fail, and then xref:02-configure-trustee.adoc#trustee-restart[restart the Trustee deployment].

* Trustee already has the necessary keys to run all the next examples.
** Refer xref:02-configure-trustee.adoc#trustee-key[here] if you want to change Trustee secrets or add new ones. Remember that after the change you need to xref:02-configure-trustee.adoc#trustee-restart[restart the Trustee deployment].

* CoCo CVM root disk size is `10`.
** Refer xref:02-configure-osc.adoc#pp-cm[here (`ROOT_VOLUME_SIZE`)] to change it. Minimum has to be `6`. Remember that after the change you need to xref:02-configure-osc.adoc#pp-restart[restart the OSC daemonset].

[tabs]
====
RHDP workshop::
+
[source,sh,role="execute",subs=attributes+]
----
export AZURE_RESOURCE_GROUP={azure_resource_group}

curl -L https://raw.githubusercontent.com/confidential-devhub/workshop-on-ARO-showroom/refs/heads/main/helpers/configure.sh -o configure.sh

chmod +x configure.sh

./configure.sh
----

ARO::
+
[source,sh,role=execute]
----
curl -L https://raw.githubusercontent.com/confidential-devhub/workshop-on-ARO-showroom/refs/heads/main/helpers/configure.sh -o configure-aro.sh

chmod +x configure-aro.sh

./configure-aro.sh
----

Azure self managed::
+
[source,sh,role=execute]
----
curl -L https://raw.githubusercontent.com/confidential-devhub/workshop-on-ARO-showroom/refs/heads/main/helpers/configure.sh -o configure-az.sh

chmod +x configure-az.sh

./configure-az.sh
----
====


Now that the configuration is complete, let's run some example!